
export enum CategoryTypeEnum {
    ARTICLE = 'Article',
    FEATURE_TYPE = "FEATURE_TYPE", // TRẠNG THÁI BÀI VIẾT
    BOOK_TYPE = "BOOK_TYPE", // LOẠI SÁCH
    BOOK_CATEGORY = "BOOK_CATEGORY", // DANH MỤC SÁCH
    BOOK_STATUS = "BOOK_STATUS", // TRẠNG THÁI ĐĂNG TẢI SÁCH
    TEMPLATE_TYPE = "TEMPLATE_TYPE",
    EVENT_STATUS = "EVENT_STATUS",
}
