
export enum CategoryCodeEnum {
    FEATURE_MENU = 'FEATURE_MENU',
    FEATURE_OTHERS = 'FEATURE_OTHERS',
    EBOOK = 'EBOOK',
    EPUB_BOOK = 'EPUB_BOOK',
    PDF_BOOK = 'PDF_BOOK',
    // BOOK_CATEGORY
    BOOK_CATEGORY_FICTION = 'BOOK_CATEGORY_FICTION',
    BOOK_CATEGORY_NON_FICTION = 'BOOK_CATEGORY_NON_FICTION',
    BOOK_CATEGORY_CHILDREN = 'BOOK_CATEGORY_CHILDREN',
    BOOK_CATEGORY_TEEN = 'BOOK_CATEGORY_TEEN',
    BOOK_CATEGORY_ADULT = 'BOOK_CATEGORY_ADULT',
    BOOK_CATEGORY_OTHER = 'BOOK_CATEGORY_OTHER',

    // BOOK_CATEGORY SUB-FICTION
    BOOK_CATEGORY_ROMANCE = 'BOOK_CATEGORY_ROMANCE',
    BOOK_CATEGORY_FANTASY = 'BOOK_CATEGORY_FANTASY',
    BOOK_CATEGORY_SCIFI = 'BOOK_CATEGORY_SCIFI',
    BOOK_CATEGORY_MYSTERY = 'BOOK_CATEGORY_MYSTERY',
    BOOK_CATEGORY_HISTORICAL_FICTION = 'BOOK_CATEGORY_HISTORICAL_FICTION',
    BOOK_CATEGORY_CLASSICS = 'BOOK_CATEGORY_CLASSICS',

    // BOOK_CATEGORY SUB-NON-FICTION
    BOOK_CATEGORY_SELF_HELP = 'BOOK_CATEGORY_SELF_HELP',
    BOOK_CATEGORY_BUSINESS = 'BOOK_CATEGORY_BUSINESS',
    BOOK_CATEGORY_BIOGRAPHY = 'BOOK_CATEGORY_BIOGRAPHY',
    BOOK_CATEGORY_HISTORY = 'BOOK_CATEGORY_HISTORY',
    BOOK_CATEGORY_SCIENCE = 'BOOK_CATEGORY_SCIENCE',
    BOOK_CATEGORY_PHILOSOPHY = 'BOOK_CATEGORY_PHILOSOPHY',

    // BOOK_CATEGORY SUB-CHILDREN
    BOOK_CATEGORY_CHILDREN_PICTURE = 'BOOK_CATEGORY_CHILDREN_PICTURE',
    BOOK_CATEGORY_CHILDREN_FAIRY = 'BOOK_CATEGORY_CHILDREN_FAIRY',
    BOOK_CATEGORY_CHILDREN_EDUCATION = 'BOOK_CATEGORY_CHILDREN_EDUCATION',

    // BOOK_CATEGORY SUB-TEEN
    BOOK_CATEGORY_TEEN_FICTION = 'BOOK_CATEGORY_TEEN_FICTION',
    BOOK_CATEGORY_TEEN_SKILLS = 'BOOK_CATEGORY_TEEN_SKILLS',

    // BOOK_CATEGORY NEW PARENTS & SUBS
    BOOK_CATEGORY_EDUCATION = 'BOOK_CATEGORY_EDUCATION',
    BOOK_CATEGORY_LANGUAGES = 'BOOK_CATEGORY_LANGUAGES',
    BOOK_CATEGORY_IT = 'BOOK_CATEGORY_IT',
    BOOK_CATEGORY_ACADEMIC = 'BOOK_CATEGORY_ACADEMIC',

    BOOK_CATEGORY_LIFESTYLE = 'BOOK_CATEGORY_LIFESTYLE',
    BOOK_CATEGORY_COOKING = 'BOOK_CATEGORY_COOKING',
    BOOK_CATEGORY_TRAVEL = 'BOOK_CATEGORY_TRAVEL',
    BOOK_CATEGORY_PARENTING = 'BOOK_CATEGORY_PARENTING',
    // BOOK_STATUS
    BOOK_STATUS_PENDING = 'BOOK_STATUS_PENDING',
    BOOK_STATUS_APPROVED = 'BOOK_STATUS_APPROVED',
    BOOK_STATUS_REJECTED = 'BOOK_STATUS_REJECTED',
}
