export enum InteractionType {
  LIKE = 'like',
  DISLIKE = 'dislike',
  BOOKMARK = 'bookmark',
  SHARE = 'share',
  VIEW = 'view',
  COMMENT = 'comment',
  RATING = 'rating',
  FOLLOW = 'follow',
  UNFOLLOW = 'unfollow',
  FAVORITE = 'favorite',
  ARCHIVED = 'archived',
  PUBLIC = 'public',
  DOWNLOAD = 'download',
  READ = 'read',
  // for reading progress
  READING = 'reading',
  TTS = 'tts',
  CONVERT = 'convert',
  UPLOAD = 'upload',
  REPORT_BROKEN_LINK = 'report_broken_link',
}
